const SEAT_TYPE = {
  BUSINESS: "BUSINESS",
  ECONOMY: "ECONOMY",
  PREMIUM_ECONOMY: "PREMIUM_ECONOMY",
  FIRST_CLASS: "FIRST_CLASS",
};

const USER_ROLES = {
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
  FLIGHT_COMPANY: "FLIGHT_COMPANY",
};


module.exports = {
  SEAT_TYPE,
  USER_ROLES
};
